services:
  # Web service for the full-stack app
  - type: web
    name: vishal-cycle-store
    env: node
    region: oregon
    plan: free
    buildCommand: NODE_ENV=development npm install --legacy-peer-deps && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: MONGO_URI
        sync: false  # You'll set this in Render dashboard
      - key: PORT
        value: 10000
    autoDeploy: true
